source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'airfightSex' do
    
    pod 'AFNetworking'
    #    pod  'JSPatch'
    pod 'IQKeyboardManagerSwift'
    
end
