source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'airfightSex' do
    
    pod 'AFNetworking' ,'~> 3.1.0'
    #    pod  'JSPatch'
    pod 'IQKeyboardManagerSwift','~> 4.0.6'
    pod 'YTKNetwork','~> 2.0.1'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SwiftyJSON','3.0.0'
    
end
